hook:
 # Automatically choose, if set to false it'll select the manual string
 automated: true
 # Choose the plugin name for the hook, which can be PermissionsEx or Vault
 manual: "Vault"

# Ability to change the usage of the command
command:
 # The main label for the command (Only changes on server start up, or reload)
 label: "staffdisplay"
 # Any other ways the command should be accessed (Only changes on server start up, or reload)
 aliases:
  - "staffd"
  - "sd"
 # The base permission, following can be used:
 # .use and .reload
 permission: "staffdisplay."

# The mechanism which checks how often the plugin should update the GUI
staff-updater:
  # How long should it wait per update, this is in seconds
  # Default value is 5 minutes
  # (Only changes on server start up, or reload)
  delay: 300

# Information related to the menu which opens
menu:
 # The title of the menu
 title: "Our Staff Members"

 # Section which allows you to configure what each rank/item looks like
 # The plugin will check if there is content for each rank and if not it
 # will automatically default to using the default item, allowing you to
 # have certain ranks looking different from others
 items:
  default:
   # The display name of the item
   display: "&c{username}"
   # The lore of the item
   lore:
    - "&6Staff Member"
    - "&7IGN: &e&l{username}"
    - "&7Rank: &e&l{rank}"

# Which ranks should be display in the menu and in which order
# Sorted from top to bottom
ranks:
 - "Owner"
 - "Admin"

# Any messages that are sent to the user
messages:
 no-permission: "&cYou do not have permission to execute this command."
 opened: "&aStaff menu has opened!"
 reloaded: "&aConfig has been reloaded!"
 invalid-subcommand: "&cInvalid sub-command."