name: StaffDisplay
version: ${project.version}-${git.commit.id.abbrev}
main: xyz.tehneon.plugins.staffdisplay.StaffDisplay
authors: [TehNeon]
description: ${project.description}

softdepend: [PermissionsEx, Vault]